version: '3.7'
services:
  #  web:
  #    build:
  #      context: ad-ctf-paas-web
  #      network: host
  #      args:
  #        - API_URL=http://${SERVER_API}
  #    container_name: web
  #    ports:
  #      - "3333:3000"
  #    depends_on:
  #      - api

  api:
    image: explabs/ad-ctf-paas-api:latest
    container_name: api
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - PROMETHEUS=http://prometheus:9090
      - OVPN_ADMIN=http://openvpn:9000
      - MONGODB=mongodb://mongo:27017
      - REDIS=redis:6379
    ports:
      - "80:8080"
    volumes:
      - ./configs/config.yml:/api/config.yml
      - ./scripts:/api/scripts
    depends_on:
      - mongo
      - redis
      - service-manager
      - ovpn-admin
      - openvpn
      - fileserver

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${ADMIN_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/

  openvpn:
    container_name: openvpn
    image: flant/ovpn-admin:openvpn-1.7.5
    command: /etc/openvpn/setup/configure.sh
    cap_add:
      - NET_ADMIN
    ports:
      - "7777:1194" # for openvpn
      - "9000:9000" # for ovpn-admin because of network_mode
    volumes:
      - ./openvpn/setup/openvpn.conf:/etc/openvpn/setup/openvpn.conf
      - ./openvpn/easyrsa_master:/etc/openvpn/easyrsa
      - ./openvpn/ccd_master:/etc/openvpn/ccd

  ovpn-admin:
    container_name: ovpn-admin
    image: flant/ovpn-admin:1.7.5
    command: /app/ovpn-admin --listen.port="9000" --ovpn.server="${SERVER_IP}:7777:tcp" --easyrsa.path="/mnt/easyrsa" --easyrsa.index-path="/mnt/easyrsa/pki/index.txt" --ccd --ccd.path="/mnt/ccd" --auth.password --auth.db="/mnt/easyrsa/pki/users.db"
    network_mode: service:openvpn
    volumes:
      - ./openvpn/easyrsa_master:/mnt/easyrsa
      - ./openvpn/ccd_master:/mnt/ccd

  fileserver:
    container_name: fileserver
    image: explabs/fileserver
    volumes:
      - ./tasks:/tasks
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:

networks:
  ad-paas-net:
